apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitjendockub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitjendockub
  template:
    metadata:
      labels:
        app: gitjendockub
    spec:
      containers:
      - name: gitjendockub
        image: karimbr/gitjendockub:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gitjendockub-service
spec:
  type: LoadBalancer
  selector:
    app: gitjendockub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
